spring.application.name=otzovichok
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?\
  ssl=true\
  &sslmode=require\
  &prepareThreshold=0\
  &preparedStatementCacheQueries=0\
  &preparedStatementCacheSizeMiB=0
spring.datasource.username=postgres.gxxhhvpylniuiwgerslt
spring.datasource.password=goidazov
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1